#This abstracts the application source files selected by the user.

APP_C_SOURCE_CortexM0p=\
	armgcc/startup/startup_psoc62_cm0plus.S\
	Source/sio.c\
	system_psoc62_cm0plus.c\
	Source/iothub_ll_telemetry_sample.c\
	Source/FreeRTOS/10.0.1/Source/portable/GCC/CM0/port.c\
	Source/FreeRTOS/10.0.1/Source/portable/MemMang/heap_4.c\
	Source/FreeRTOS/10.0.1/Source/croutine.c\
	Source/FreeRTOS/10.0.1/Source/event_groups.c\
	Source/FreeRTOS/10.0.1/Source/list.c\
	Source/FreeRTOS/10.0.1/Source/queue.c\
	Source/FreeRTOS/10.0.1/Source/stream_buffer.c\
	Source/FreeRTOS/10.0.1/Source/tasks.c\
	Source/FreeRTOS/10.0.1/Source/timers.c\
	Source/LwIP/src/api/api_lib.c\
	Source/LwIP/src/api/api_msg.c\
	Source/LwIP/src/api/err.c\
	Source/LwIP/src/api/netbuf.c\
	Source/LwIP/src/api/netdb.c\
	Source/LwIP/src/api/netifapi.c\
	Source/LwIP/src/api/sockets.c\
	Source/LwIP/src/api/tcpip.c\
	Source/LwIP/src/core/ipv4/autoip.c\
	Source/LwIP/src/core/ipv4/dhcp.c\
	Source/LwIP/src/core/ipv4/etharp.c\
	Source/LwIP/src/core/ipv4/icmp.c\
	Source/LwIP/src/core/ipv4/igmp.c\
	Source/LwIP/src/core/ipv4/ip4.c\
	Source/LwIP/src/core/ipv4/ip4_addr.c\
	Source/LwIP/src/core/ipv4/ip4_frag.c\
	Source/LwIP/src/core/ipv6/dhcp6.c\
	Source/LwIP/src/core/ipv6/ethip6.c\
	Source/LwIP/src/core/ipv6/icmp6.c\
	Source/LwIP/src/core/ipv6/inet6.c\
	Source/LwIP/src/core/ipv6/ip6.c\
	Source/LwIP/src/core/ipv6/ip6_addr.c\
	Source/LwIP/src/core/ipv6/ip6_frag.c\
	Source/LwIP/src/core/ipv6/mld6.c\
	Source/LwIP/src/core/ipv6/nd6.c\
	Source/LwIP/src/core/def.c\
	Source/LwIP/src/core/dns.c\
	Source/LwIP/src/core/inet_chksum.c\
	Source/LwIP/src/core/init.c\
	Source/LwIP/src/core/ip.c\
	Source/LwIP/src/core/mem.c\
	Source/LwIP/src/core/memp.c\
	Source/LwIP/src/core/netif.c\
	Source/LwIP/src/core/pbuf.c\
	Source/LwIP/src/core/raw.c\
	Source/LwIP/src/core/stats.c\
	Source/LwIP/src/core/sys.c\
	Source/LwIP/src/core/tcp.c\
	Source/LwIP/src/core/tcp_in.c\
	Source/LwIP/src/core/tcp_out.c\
	Source/LwIP/src/core/timeouts.c\
	Source/LwIP/src/core/udp.c\
	Source/LwIP/src/netif/ethernet.c\
	Source/LwIP/src/netif/ethernetif.c\
	Source/LwIP/src/netif/lowpan6.c\
	Source/LwIP/src/netif/slipif.c\
	Source/LwIP/src/sys_arch.c\
	Source/mbedtls_open/library/aes.c\
	Source/mbedtls_open/library/aesni.c\
	Source/mbedtls_open/library/arc4.c\
	Source/mbedtls_open/library/aria.c\
	Source/mbedtls_open/library/asn1parse.c\
	Source/mbedtls_open/library/asn1write.c\
	Source/mbedtls_open/library/base64.c\
	Source/mbedtls_open/library/bignum.c\
	Source/mbedtls_open/library/blowfish.c\
	Source/mbedtls_open/library/camellia.c\
	Source/mbedtls_open/library/ccm.c\
	Source/mbedtls_open/library/certs.c\
	Source/mbedtls_open/library/chacha20.c\
	Source/mbedtls_open/library/chachapoly.c\
	Source/mbedtls_open/library/cipher.c\
	Source/mbedtls_open/library/cipher_wrap.c\
	Source/mbedtls_open/library/cmac.c\
	Source/mbedtls_open/library/ctr_drbg.c\
	Source/mbedtls_open/library/debug.c\
	Source/mbedtls_open/library/des.c\
	Source/mbedtls_open/library/dhm.c\
	Source/mbedtls_open/library/ecdh.c\
	Source/mbedtls_open/library/ecdsa.c\
	Source/mbedtls_open/library/ecjpake.c\
	Source/mbedtls_open/library/ecp.c\
	Source/mbedtls_open/library/ecp_curves.c\
	Source/mbedtls_open/library/entropy.c\
	Source/mbedtls_open/library/entropy_poll.c\
	Source/mbedtls_open/library/error.c\
	Source/mbedtls_open/library/gcm.c\
	Source/mbedtls_open/library/havege.c\
	Source/mbedtls_open/library/hkdf.c\
	Source/mbedtls_open/library/hmac_drbg.c\
	Source/mbedtls_open/library/md.c\
	Source/mbedtls_open/library/md_wrap.c\
	Source/mbedtls_open/library/md2.c\
	Source/mbedtls_open/library/md4.c\
	Source/mbedtls_open/library/md5.c\
	Source/mbedtls_open/library/memory_buffer_alloc.c\
	Source/mbedtls_open/library/net_sockets.c\
	Source/mbedtls_open/library/nist_kw.c\
	Source/mbedtls_open/library/oid.c\
	Source/mbedtls_open/library/padlock.c\
	Source/mbedtls_open/library/pem.c\
	Source/mbedtls_open/library/pk.c\
	Source/mbedtls_open/library/pk_wrap.c\
	Source/mbedtls_open/library/pkcs5.c\
	Source/mbedtls_open/library/pkcs11.c\
	Source/mbedtls_open/library/pkcs12.c\
	Source/mbedtls_open/library/pkparse.c\
	Source/mbedtls_open/library/pkwrite.c\
	Source/mbedtls_open/library/platform.c\
	Source/mbedtls_open/library/platform_util.c\
	Source/mbedtls_open/library/poly1305.c\
	Source/mbedtls_open/library/ripemd160.c\
	Source/mbedtls_open/library/rsa.c\
	Source/mbedtls_open/library/rsa_internal.c\
	Source/mbedtls_open/library/sha1.c\
	Source/mbedtls_open/library/sha256.c\
	Source/mbedtls_open/library/sha512.c\
	Source/mbedtls_open/library/ssl_cache.c\
	Source/mbedtls_open/library/ssl_ciphersuites.c\
	Source/mbedtls_open/library/ssl_cli.c\
	Source/mbedtls_open/library/ssl_cookie.c\
	Source/mbedtls_open/library/ssl_srv.c\
	Source/mbedtls_open/library/ssl_ticket.c\
	Source/mbedtls_open/library/ssl_tls.c\
	Source/mbedtls_open/library/threading.c\
	Source/mbedtls_open/library/timing.c\
	Source/mbedtls_open/library/version.c\
	Source/mbedtls_open/library/version_features.c\
	Source/mbedtls_open/library/x509.c\
	Source/mbedtls_open/library/x509_create.c\
	Source/mbedtls_open/library/x509_crl.c\
	Source/mbedtls_open/library/x509_crt.c\
	Source/mbedtls_open/library/x509_csr.c\
	Source/mbedtls_open/library/x509write_crt.c\
	Source/mbedtls_open/library/x509write_csr.c\
	Source/mbedtls_open/library/xtea.c\
	Source/azure_iot_sdk/c-utility/adapters/agenttime.c\
	Source/azure_iot_sdk/c-utility/adapters/platform_freertos.c\
	Source/azure_iot_sdk/c-utility/adapters/socketio_mbed.c\
	Source/azure_iot_sdk/c-utility/adapters/tlsio_mbedtls.c\
	Source/azure_iot_sdk/c-utility/adapters/uniqueid_stub.c\
	Source/azure_iot_sdk/c-utility/src/crt_abstractions.c\
	Source/azure_iot_sdk/c-utility/src/xlogging.c\
	Source/azure_iot_sdk/c-utility/src/map.c\
	Source/azure_iot_sdk/c-utility/src/strings.c\
	Source/azure_iot_sdk/c-utility/src/buffer.c\
	Source/azure_iot_sdk/c-utility/src/doublylinkedlist.c\
	Source/azure_iot_sdk/c-utility/src/singlylinkedlist.c\
	Source/azure_iot_sdk/c-utility/src/constbuffer.c\
	Source/azure_iot_sdk/c-utility/src/string_token.c\
	Source/azure_iot_sdk/c-utility/src/string_tokenizer.c\
	Source/azure_iot_sdk/c-utility/src/xio.c\
	Source/azure_iot_sdk/c-utility/src/urlencode.c\
	Source/azure_iot_sdk/c-utility/src/gballoc.c\
	Source/azure_iot_sdk/c-utility/src/optionhandler.c\
	Source/azure_iot_sdk/c-utility/src/vector.c\
	Source/azure_iot_sdk/c-utility/src/sastoken.c\
	Source/azure_iot_sdk/c-utility/src/base64_2.c\
	Source/azure_iot_sdk/c-utility/src/hmacsha256.c\
	Source/azure_iot_sdk/c-utility/src/hmac.c\
	Source/azure_iot_sdk/c-utility/src/usha.c\
	Source/azure_iot_sdk/c-utility/src/uuid.c\
	Source/azure_iot_sdk/c-utility/src/sha224.c\
	Source/azure_iot_sdk/c-utility/src/sha384-512.c\
	Source/azure_iot_sdk/c-utility/src/sha1_1.c\
	Source/azure_iot_sdk/c-utility/src/consolelogger.c\
	Source/azure_iot_sdk/c-utility/pal/freertos/threadapi.c\
	Source/azure_iot_sdk/c-utility/pal/freertos/tickcounter.c\
	Source/azure_iot_sdk/c-utility/pal/freertos/lock.c\
	Source/azure_iot_sdk/c-utility/Socket/src/Endpoint.cpp\
	Source/azure_iot_sdk/c-utility/Socket/src/Socket.cpp\
	Source/azure_iot_sdk/c-utility/Socket/src/TCPSocketConnection.cpp\
	Source/azure_iot_sdk/c-utility/Socket/src/tcpsocketconnection_c.cpp\
	Source/azure_iot_sdk/c-utility/Socket/src/TCPSocketServer.cpp\
	Source/azure_iot_sdk/c-utility/Socket/src/UDPSocket.cpp\
	Source/azure_iot_sdk/iothub_client/src/iothub.c\
	Source/azure_iot_sdk/iothub_client/src/iothub_device_client_ll.c\
	Source/azure_iot_sdk/iothub_client/src/iothub_message.c\
	Source/azure_iot_sdk/iothub_client/src/iothub_client_core_ll.c\
	Source/azure_iot_sdk/iothub_client/src/iothub_client_ll_uploadtoblob.c\
	Source/azure_iot_sdk/iothub_client/src/iothub_client_diagnostic.c\
	Source/azure_iot_sdk/iothub_client/src/iothub_client_authorization.c\
	Source/azure_iot_sdk/iothub_client/src/iothubtransport.c\
	Source/azure_iot_sdk/iothub_client/src/iothubtransportamqp.c\
	Source/azure_iot_sdk/iothub_client/src/iothubtransport_amqp_common.c\
	Source/azure_iot_sdk/iothub_client/src/iothubtransportamqp_methods.c\
	Source/azure_iot_sdk/iothub_client/src/iothubtransport_amqp_connection.c\
	Source/azure_iot_sdk/iothub_client/src/iothubtransport_amqp_messenger.c\
	Source/azure_iot_sdk/iothub_client/src/iothubtransport_amqp_device.c\
	Source/azure_iot_sdk/iothub_client/src/iothub_client_retry_control.c\
	Source/azure_iot_sdk/iothub_client/src/iothubtransport_amqp_telemetry_messenger.c\
	Source/azure_iot_sdk/iothub_client/src/iothubtransport_amqp_twin_messenger.c\
	Source/azure_iot_sdk/iothub_client/src/iothubtransport_amqp_cbs_auth.c\
	Source/azure_iot_sdk/iothub_client/src/uamqp_messaging.c\
	Source/azure_iot_sdk/iothub_client/src/message_queue.c\
	Source/azure_iot_sdk/uamqp/src/amqpvalue.c\
	Source/azure_iot_sdk/uamqp/src/amqpvalue_to_string.c\
	Source/azure_iot_sdk/uamqp/src/amqp_management.c\
	Source/azure_iot_sdk/uamqp/src/amqp_definitions.c\
	Source/azure_iot_sdk/uamqp/src/sasl_mssbcbs.c\
	Source/azure_iot_sdk/uamqp/src/message_sender.c\
	Source/azure_iot_sdk/uamqp/src/message_receiver.c\
	Source/azure_iot_sdk/uamqp/src/messaging.c\
	Source/azure_iot_sdk/uamqp/src/link.c\
	Source/azure_iot_sdk/uamqp/src/message.c\
	Source/azure_iot_sdk/uamqp/src/sasl_mechanism.c\
	Source/azure_iot_sdk/uamqp/src/connection.c\
	Source/azure_iot_sdk/uamqp/src/session.c\
	Source/azure_iot_sdk/uamqp/src/cbs.c\
	Source/azure_iot_sdk/uamqp/src/async_operation.c\
	Source/azure_iot_sdk/uamqp/src/amqp_frame_codec.c\
	Source/azure_iot_sdk/uamqp/src/frame_codec.c\
	Source/azure_iot_sdk/uamqp/src/saslclientio.c\
	Source/azure_iot_sdk/uamqp/src/sasl_frame_codec.c\
	cy_ipc_config.c\
	stdio_user.c

APP_ASM_SOURCE_CortexM0p=\

APP_LIBS_CortexM0p=\

APP_C_SOURCE_CortexM4=\
	main_cm4.c\
	armgcc/startup/startup_psoc62_cm4.S\
	system_psoc62_cm4.c\
	cy_ipc_config.c\
	stdio_user.c

APP_ASM_SOURCE_CortexM4=\

APP_LIBS_CortexM4=\

