/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* I2C_SCB_IRQ */
#define I2C_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define I2C_SCB_IRQ__INTC_CORTEXM0P_MUX 8u
#define I2C_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define I2C_SCB_IRQ__INTC_NUMBER 44u
#define I2C_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define I2C_SCB_IRQ_INTC_CORTEXM0P_MUX 8u
#define I2C_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define I2C_SCB_IRQ_INTC_NUMBER 44u

/* UART_1_SCB_IRQ */
#define UART_1_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define UART_1_SCB_IRQ__INTC_CORTEXM0P_MUX 9u
#define UART_1_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define UART_1_SCB_IRQ__INTC_NUMBER 46u
#define UART_1_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define UART_1_SCB_IRQ_INTC_CORTEXM0P_MUX 9u
#define UART_1_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define UART_1_SCB_IRQ_INTC_NUMBER 46u

/* UART_2_SCB_IRQ */
#define UART_2_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define UART_2_SCB_IRQ__INTC_CORTEXM0P_MUX 10u
#define UART_2_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define UART_2_SCB_IRQ__INTC_NUMBER 42u
#define UART_2_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define UART_2_SCB_IRQ_INTC_CORTEXM0P_MUX 10u
#define UART_2_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define UART_2_SCB_IRQ_INTC_NUMBER 42u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
